import { Project } from '@/app/src/types';

export const projects: Project[] = [
  {
    id: 'anakeedmart',
    title: 'AnakeedMart',
    description:
      'AnakeedMart is an online grocery delivery platform designed to provide a seamless shopping experience for users. Developed using NodeJS and React for backend and frontend services with React Native for mobile app, providing a cohesive experience across web and mobile platforms. MongoDB for data storage and AWS for cloud services with Jira for project management. The platform played a pivotal role during COVID and facilitated over 10,000 orders within the first six months, resulting in a 70% increase in user engagement and a 40% reduction in order processing times. Customers appreciated the live tracking feature, contributing to a 50% improvement in satisfaction ratings.',
    image: '/assets/images/Anakeed_Mart.webp',
    modalImage: '/assets/images/Anakeed_Mart.webp',
    year: '2019-2020',
    category: 'E-commerce',
    imagePosition: 'object-top',
    tags: ['NodeJS', 'React', 'React Native', 'MongoDB', 'AWS', 'Jest', 'Cypress'],
    url: '',
  },
  {
    id: 'bridge18',
    title: 'Bridge18',
    description:
      'Bridge18 is a smart freight network connecting carriers to brokers, aimed at optimizing freight management and reducing operational costs. Developed using NodeJS and PHP for backend services, React and Angular for frontend development. Integrated AWS for hosting and cloud infrastructure with MySQL as primary database. Socket.io was used for real-time communication features like load tracking and carrier updates. The platform improved load management efficiency by 30% and reduced operational costs by 25%. It facilitated better communication between carriers and brokers, resulting in significant increase in user satisfaction and a 50% improvement in load-matching efficiency.',
    image: '/assets/images/bridge_18_small.png',
    modalImage: '/assets/images/bridge_18_large.png',
    year: '2018-2019',
    category: 'Logistics',
    tags: ['NodeJS', 'PHP', 'React', 'Angular', 'Vue.js', 'MySQL', 'AWS', 'Socket.io'],
    url: 'https://bridge18.com',
  },
  {
    id: 'travelsighted',
    title: 'TravelSighted',
    description:
      'TravelSighted is a platform for tourists to explore and discover new destinations with personalized recommendations and interactive features. Developed using React Native for mobile application and .NET for backend services. Frontend built using TypeScript React and Semantic-UI, providing an intuitive user experience. Integrated Azure for hosting and cloud services with maps APIs for interactive location-based features. Redux-toolkit implemented for state management and GraphQL for efficient data querying. The platform saw a 45% increase in user engagement and a 30% rise in user retention. The interactive features and personalized recommendations contributed to a 40% improvement in customer satisfaction and a 35% increase in bookings through the platform.',
    image: '/assets/images/travel_sighted_small.png',
    modalImage: '/assets/images/travel_sighted_large.png',
    year: '2018-2019',
    category: 'Travel',
    imagePosition: 'object-left-top',
    tags: ['.NET', 'React', 'React Native', 'TypeScript', 'Semantic-UI', 'MongoDB', 'Azure', 'GraphQL', 'Redux'],
    url: 'https://travelsighted.com',
  },
  {
    id: 'urdupoint',
    title: 'UrduPoint',
    description:
      'UrduPoint is a comprehensive news application designed to deliver real-time news updates, articles, and videos to users in the Urdu language. Developed using PHP for backend services and React Native for mobile application. Frontend developed using React and Semantic-UI, providing an intuitive user interface. MySQL for database management and AWS for cloud infrastructure. Integrated Socket.io for real-time news updates and Firebase messaging for real-time notifications. Integrated several ad/monetization platforms like Facebook ads and Google Ad Manager. The mobile app achieved over 500,000 downloads within the first year, resulting in a 56% increase in user engagement and a 40% rise in ad revenue. The platform\'s real-time news updates and user-friendly interface contributed to a 50% improvement in customer satisfaction.',
    image: '/assets/images/urdupoint_small.png',
    modalImage: '/assets/images/urdupoint_large.png',
    year: '2017-2019',
    category: 'Media',
    tags: ['PHP', 'React', 'React Native', 'MySQL', 'AWS', 'Socket.io', 'Firebase'],
    url: 'https://urdupoint.com',
  },
  {
    id: 'convoy',
    title: 'Convoy',
    description:
      'Convoy is a smart freight network aimed at reducing carbon emissions by optimizing load management and reducing empty miles. Developed using NodeJS and Express for backend services and React for frontend development. Frontend built using Semantic-UI and Material-UI, providing an intuitive user experience. AWS employed for cloud services with MongoDB as primary database. Integrated Socket.io for real-time updates and Redis for session management. Vue.js utilized for interactive dashboards. Convoy had impactful results in the logistics and freight network industry, offering a smarter, more eco-friendly way for freight services to reduce carbon emissions. The comprehensive freight management system empowered logistics companies to optimize their supply chains and connect with brokers, ultimately helping reduce empty truck miles and creating more efficient routes with reduced environmental footprint.',
    image: '/assets/images/Convoy_small.png',
    modalImage: '/assets/images/Convoy_large.png',
    year: '2016-2017',
    category: 'Green Tech',
    tags: ['NodeJS', 'Express', 'React', 'Vue.js', 'MongoDB', 'Redis', 'AWS', 'Socket.io'],
    url: 'https://convoy.com',
  },
  {
    id: 'remindmelater',
    title: 'RemindMeLater',
    description:
      'RemindMeLater is an online shopping assistant that allows users to save items for later purchases and receive notifications when items are back in stock or on sale. Developed using .NET for backend services and React Native for mobile application. Frontend developed using React and Semantic-UI, providing an intuitive and engaging user interface. Integrated Azure for hosting and cloud services with PostgreSQL for database management. React utilized for interactive features like product tracking and notifications, while GraphQL used for efficient data querying. The launch revolutionized the way users managed their online shopping. With a simple interface that allowed users to save items they liked and set reminders, the app offered a solution to impulsive shopping while ensuring customers didn\'t miss out on products they were genuinely interested in. The app\'s efficiency in reminding users of their potential purchases significantly enhanced their shopping experience.',
    image: '/assets/images/remindmelater.png',
    modalImage: '/assets/images/remind_me_later_large.jpg',
    year: '2016-2017',
    category: 'Shopping',
    tags: ['.NET', 'React', 'React Native', 'PostgreSQL', 'Azure', 'GraphQL'],
    url: 'https://apps.apple.com/us/app/remindmelater-io/id1558029215',
  },
  // {
  //   id: 'amz2go',
  //   title: 'Amz2go.com',
  //   description:
  //     'Amz2go is a platform designed for trading and e-commerce purposes, providing users with tools to manage and track their trading activities. Developed using NodeJS and Express for backend services with Java for Android and Objective-C for iOS mobile applications. Frontend developed using React and Semantic-UI, providing an intuitive user interface. AWS employed for hosting and cloud services with Django used for specific backend features. MongoDB for database management. The platform for trade and e-commerce saw great adoption due to its seamless interface and user-friendly features. It allowed businesses to efficiently manage their trade operations, create stronger links with vendors, and maintain customer satisfaction through well-organized workflows. The app\'s success was largely due to its intuitive system for managing product listings and transactions.',
  //   image: '/assets/images/work_3.png',
  //   modalImage: '/assets/images/work_3.png',
  //   year: '2015-2016',
  //   category: 'Trading',
  //   tags: ['NodeJS', 'Django', 'React', 'Vue.js', 'Android', 'iOS', 'MongoDB', 'AWS'],
  //   url: 'https://amz2go.com',
  // },
  {
    id: 'ezymigrate',
    title: 'EzyMigrate',
    description:
      'EzyMigrate is an immigration advisory platform designed to help businesses manage their client interactions, documents, and processes. Developed using .NET for backend services and React for frontend development. Integrated Azure for hosting and cloud services with PostgreSQL for database management. Frontend developed using Semantic-UI and Material-UI, providing an intuitive user experience. The introduction of EzyMigrate had a significant impact on immigration consultants and advisors. The software made the entire process of handling immigration cases smoother and more efficient. By providing an all-in-one platform for managing client information, applications, and compliance requirements, EzyMigrate simplified the workload for advisors and increased operational efficiency, leading to improved client outcomes.',
    image: '/assets/images/ezy_migrate.jpeg',
    modalImage: '/assets/images/ezymigrate_large.png',
    year: '2014-2015',
    category: 'Legal Services',
    tags: ['.NET', 'React', 'PostgreSQL', 'Azure', 'Semantic-UI', 'Material-UI'],
    url: 'https://ezymigrate.co.nz',
  },
  {
    id: 'reistar',
    title: 'REIStar',
    description:
      'REIStar is a real estate platform designed to simplify property buying and selling processes by providing tools for listing management, property searches, and secure transactions. Developed using Laravel and PHP for backend services with HTML, CSS, jQuery and Bootstrap for frontend development. MySQL for database management and AWS for cloud infrastructure. GitHub integrated for version control with Jira for project management. REIStar successfully enhanced the way property transactions were conducted. By offering a digital platform where buyers and sellers could connect seamlessly, the platform streamlined the entire process of buying and selling real estate. Its user-friendly interface and comprehensive features made it easier for users to list, search, and close property deals.',
    image: '/assets/images/reistar.png',
    modalImage: '/assets/images/reistar_large.png',
    year: '2013-2014',
    category: 'Real Estate',
    tags: ['Laravel', 'PHP', 'MySQL', 'jQuery', 'Bootstrap', 'AWS'],
    url: 'https://reistar.com',
  },
  // {
  //   id: 'avatar',
  //   title: 'Avatar.co.nz',
  //   description:
  //     'Avatar is an SEO service platform designed to help businesses improve their online presence through search engine optimization. Developed using Laravel and PHP for backend services with HTML, CSS and jQuery for frontend development. MySQL for database management and AWS for cloud infrastructure. GitHub integrated for version control with Trello for project management. Avatar became an essential tool for businesses seeking to improve their online presence through SEO services. By optimizing websites for search engines, Avatar enabled companies to reach a larger audience and improve their visibility in a competitive online marketplace.',
  //   image: '/assets/images/work_2.png',
  //   modalImage: '/assets/images/work_2.png',
  //   year: '2012-2013',
  //   category: 'Marketing',
  //   tags: ['Laravel', 'PHP', 'MySQL', 'jQuery', 'AWS', 'Google Adwords'],
  //   url: 'https://avatar.co.nz',
  // },
  {
    id: 'acqyrexchange',
    title: 'AcqyrExchange',
    description:
      'AcqyrCash is a platform for gamers to convert in-game assets into real-world assets, aimed at enhancing the gaming experience and providing monetization options for players. Developed using NodeJS and Express for backend services with React Native and Angular for frontend development. PostgreSQL for database management and AWS for cloud hosting. Integrated AWS Cognito for secure user authentication with Cypress for Automation Testing. React utilized for interactive dashboards. The outcome was a unique platform for gamers to convert their in-game assets into real-world assets. The secure and scalable infrastructure, combined with user-friendly features, facilitated a smooth transaction process, increasing user engagement and providing a novel solution in the gaming industry.',
    image: '/assets/images/acqyr_exchange_small.png',
    modalImage: '/assets/images/acqyr_exchange_large.png',
    year: '2018-2019',
    category: 'Gaming',
    tags: ['NodeJS', 'Express', 'React Native', 'Angular', 'PostgreSQL', 'AWS', 'GraphQL'],
    url: 'https://acqyrexchange.com',
  },
  {
    id: 'clublacrosse',
    title: 'ClubLacrosse',
    description:
      'ClubLax is the official sports app for the sports club lacrosse, providing players and fans with real-time game statistics, player profiles, and live updates. Developed using NodeJS and Express for backend services and React Native for mobile application. Frontend built using React and Semantic-UI, providing an engaging user experience. AWS employed for hosting and cloud services with MongoDB as primary database. Integrated Socket.io for real-time updates and AWS Cognito for secure authentication. Redis used for session management with React utilized for interactive features like live game tracking and player statistics. The outcome was highly positive, as it provided users with an enhanced platform for real-time statistics, player performance data, and game insights for lacrosse clubs. The platform improved the engagement of sports teams with their supporters by offering easy access to live updates, game statistics, and performance data. The app also fostered a greater sense of community among players and fans.',
    image: '/assets/images/clublacrosse_small.png',
    modalImage: '/assets/images/clublacrosse_large.png',
    year: '2017-2018',
    category: 'Sports',
    tags: ['NodeJS', 'Express', 'React', 'React Native', 'MongoDB', 'AWS', 'Socket.io', 'Redis'],
    url: 'https://www.clublacrosse.org',
  },
  {
    id: 'nexthire',
    title: 'NextHire',
    description:
      'NextHire is a recruitment platform designed to connect job seekers with potential employers, offering features like job matching, candidate profiles, and interview scheduling. Developed using JavaScript, NodeJS, and Express for backend services and Angular for frontend development. MongoDB for managing candidate and job data with AWS for hosting and cloud services. GitHub for version control and Postman for API testing. Integrated AWS Cognito for secure authentication with AngularJS utilized for interactive dashboards and job analytics. NextHire emerged as an efficient hiring solution that made the job search and recruitment process more streamlined and dynamic. By giving candidates the opportunity to connect directly with potential employers through the platform, NextHire bridged the gap between recruiters and job seekers. This innovative approach helped reduce the time it took for candidates to get noticed by employers, creating a more interactive and faster recruitment cycle.',
    image: '/assets/images/nexthire_small.png',
    modalImage: '/assets/images/nexthire_large.png',
    year: '2017',
    category: 'Recruitment',
    tags: ['NodeJS', 'Express', 'Angular', 'MongoDB', 'AWS', 'Jest'],
    url: 'https://nexthire.in',
  },
];
